# Generated by Django 3.2.25 on 2024-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240728_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='primary_account',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_accounts',
            field=models.ManyToManyField(blank=True, help_text='The primary accounts associated with this user.', related_name='account_users', to='core.PrimaryAccount', verbose_name='primary accounts'),
        ),
        migrations.AlterField(
            model_name='primaryaccount',
            name='name',
            field=models.CharField(help_text='Required. 255 characters or fewer.', max_length=255, verbose_name='account name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Required. 255 characters or fewer. Must be a valid email address.', max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Required. 255 characters or fewer.', max_length=255, verbose_name='full name'),
        ),
    ]
