# Generated by Django 3.2.25 on 2024-07-29 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240729_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='The date and time when the user was created.', verbose_name='date created'),
            preserve_default=False,
        ),
    ]
