# Generated by Django 3.2.25 on 2024-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Required. 255 characters or fewer.', max_length=255, verbose_name='account name')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date and time when the user was created.', verbose_name='date created')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this account should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active status')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='primary_accounts',
        ),
        migrations.DeleteModel(
            name='PrimaryAccount',
        ),
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, help_text='The accounts associated with this user.', related_name='account_users', to='core.Account', verbose_name='accounts'),
        ),
    ]
